Ukol 2
DavidOsicka/PV256-Movio2 pull request #1
Opened 2016-10-04 06:33 UTC by DavidOsicka

2016-10-04 07:23 UTC, vandus commented on app/src/main/res/values/values.xml
> +    <color name="primary_dark_material_dark">#044c1f</color>
colors by mali byt v colors.xml ... samozrejme, ze to bude fungovat aj takto.

2016-10-21 15:53 UTC, DavidOsicka commented
Už jsem přesunul definice barev do colors.xml a  nejsou ve values.xml

2016-10-30 15:11 UTC, vandus requested changes
Chyba AppTheme2, asi nie je nieco commitnute. 
V styles pre v22 je nejake AppThemes2, neviem ci to ma byt AppTheme2..?

2016-10-30 15:20 UTC, DavidOsicka commented
Už jsem to opravil.
Při ukládání jsem asi špatně zmačkl ctrl a napsalo se tam "s", čehož sem si nevšiml a pushnul to.

2016-10-30 15:31 UTC, vandus approved these changes

2016-10-30 18:08 UTC, merged