Ukol 7
DavidOsicka/PV256-Movio2 pull request #6
Opened 2017-01-08 16:24 UTC by DavidOsicka

2017-01-09 22:41 UTC, vandus requested changes
Ulozeny film sa vobec nezobrazuje. Miesto obrazkov su len cierne oblasti. Myslim, ze je to kvoli porusovaniu StrictMode, ale tazko posudit. Prezri si to este raz a skus opravit.

2017-01-10 23:19 UTC, DavidOsicka commented
Neměl jsem zde tenhle problém a po projití kódu mě ani nenapadá kde by mohl nastat.
Neměl být tenhle koment k branchy ukol_8 ? Tam jsem zapomněl a omylem pushnul kus kodu, který byl jen pro testování a ukládal do databáze film beze jména a obrázků, ale platným id, který se následně syncnul.

2017-01-14 20:48 UTC, vandus commented on app/src/main/java/cz/muni/fi/pv256/movio2/uco_396537/MainActivity.java
>          isTablet = (getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_LARGE ||
Teraz som si vsimla - na riadku 65-66 je inicializacia App. Toto tam urcite nema co robit. V dobe spustenia aplikacie sa ma tato trieda zavolat sama, a v dobe spustenia MainActivity onCreate uz prebehlo.

App treba deklarovat v Manifeste v applicaiton elemente.

2017-01-14 20:57 UTC, vandus commented on app/src/main/java/cz/muni/fi/pv256/movio2/uco_396537/MainActivity.java
> +        mDetailViewFragment = new DetailViewFragment();
fragment by sa mal inicializovat staticky

2017-01-14 20:58 UTC, vandus commented on app/src/main/java/cz/muni/fi/pv256/movio2/uco_396537/MainActivity.java
> +        startService(popularMovieDownloadIntent);
nebolo by lepsie spustit jednu service a tej povedat, co chces stiahnut?

2017-01-14 21:00 UTC, vandus commented on app/src/main/java/cz/muni/fi/pv256/movio2/uco_396537/MainActivity.java
> +        if (actionBar != null) {
metoda onCreate je prilis dlha. tato cast kodu od acitonBar!=null by mohla byt v privatnej triede, nieco ako initActionBar()

2017-01-15 20:00 UTC, DavidOsicka commented on app/src/main/java/cz/muni/fi/pv256/movio2/uco_396537/MainActivity.java
>          isTablet = (getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_LARGE ||
opraveno

2017-01-15 20:00 UTC, DavidOsicka commented on app/src/main/java/cz/muni/fi/pv256/movio2/uco_396537/MainActivity.java
> +        if (actionBar != null) {
opraveno

2017-01-15 20:09 UTC, DavidOsicka commented on app/src/main/java/cz/muni/fi/pv256/movio2/uco_396537/MainActivity.java
> +        mDetailViewFragment = new DetailViewFragment();
staticky v xml, tak jak je popsáno zde https://jonassevcik.gitbooks.io/android-uvod/content/3-zivotni_cyklus.html ? To by pak ale nebylo možné v rámci jedné aktivity přepínat mezi dvěma fragmenty ne? A ve většině tutoriálu používají právě tenhle přístup, tak jsem myslel, že je ok.

2017-01-15 23:36 UTC, DavidOsicka commented on app/src/main/java/cz/muni/fi/pv256/movio2/uco_396537/MainActivity.java
> +        startService(popularMovieDownloadIntent);
opraveno

2017-01-16 21:47 UTC, vandus approved these changes

2017-01-17 08:54 UTC, merged