Ukol 8
DavidOsicka/PV256-Movio2 pull request #7
Opened 2017-01-09 18:32 UTC by DavidOsicka

2017-01-14 22:07 UTC, vandus approved these changes

2017-01-14 22:17 UTC, vandus commented on app/src/androidTest/java/cz/muni/fi/pv256/movio2/uco_396537/DatabaseManagerTest.java
> +        mContext.getContentResolver().delete(
tento test ovplyvnuje priamo data v aplikacii. skus si ulozit film do favorites a potom spustittestCreateMovie. na konci sa vymaze databaza a vymaze sa aj tebou ulozeny film. 

testy by mali typicky mat vsetky objekty, az na testovany, mockovane. pripadne mozes pouzivat na testovanie nejaku nahradnu databazu, nie priamo tu pouzivanu v aplikacii..

2017-01-14 22:19 UTC, vandus requested changes
skus opravit ten padajuci testCrateMovie test

2017-01-16 13:21 UTC, DavidOsicka commented
testCreateMovie opraven

2017-01-16 13:23 UTC, DavidOsicka commented on app/src/androidTest/java/cz/muni/fi/pv256/movio2/uco_396537/DatabaseManagerTest.java
> +        mContext.getContentResolver().delete(
Vzhledem k tomu, že i Jonáš Ševčík, to tak měl v ukázkovém projektu. A ani v tutoriálech jsem nenašel jiný způsob, jak by bylo možné mocknout nebo testovat nad jinou databází, nechal jsem to takhle. Data z databáze si však před testem zálohuji  a po testu vrátím zpět, aby byly zachovány.

2017-01-16 22:01 UTC, vandus commented
ano! to vyzera lepsie.

2017-01-16 22:01 UTC, vandus approved these changes

2017-01-17 08:55 UTC, merged